# Generated by Django 2.2.6 on 2019-10-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('Seller', 'seller'), ('Buyer', 'buyer')], max_length=50),
        ),
    ]
