# Generated by Django 2.2.6 on 2019-10-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Flats', 'FT'), ('Villas', 'VL'), ('Land', 'LD'), ('Shopping Complex', 'CX')], max_length=30),
        ),
    ]
